name: Playwright Tests
on:
  push:
    branches: [ Bug_FixingE2ETestWorkflow ]
  pull_request:
    branches: [ Bug_FixingE2ETestWorkflow ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies for Web
        run: dotnet restore src/Chirp.Web/Chirp.Web.csproj

      - name: Restore dependencies for Tests
        run: |
          dotnet restore test/Chirp.TestE2E/Chirp.TestE2E.csproj

      - name: Build Web
        run: dotnet build src/Chirp.Web/Chirp.Web.csproj --no-restore

      - name: Build Tests
        run: dotnet build test/Chirp.TestE2E/Chirp.TestE2E.csproj --no-restore

      - name: Run Web Application
        run: dotnet run --project src/Chirp.Web/Chirp.Web.csproj --urls "http://localhost:5273" &

      - name: Wait for Web Application to Start
        run: sleep 10
      
      - name: Install Playwright
        run: pwsh test/Chirp.TestE2E/bin/Debug/net8.0/playwright.ps1 install

      - name: End To End Test
        env:
          AUTHENTICATION_GITHUB_CLIENTID: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTID }}
          AUTHENTICATION_GITHUB_CLIENTSECRET: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTSECRET }}
          GITHUBTESTACCOUNTUSERNAME: ${{ secrets.GITHUBTESTACCOUNTUSERNAME }}
          GITHUBTESTACCOUNTPASSWORD: ${{ secrets.GITHUBTESTACCOUNTPASSWORD }}
        run: |
          dotnet test test/Chirp.TestE2E/Chirp.TestE2E.csproj --verbosity normal