name: Playwright Tests
on:
  push:
    branches: [ Bug_FixingE2ETestWorkflow ]
  pull_request:
    branches: [ Bug_FixingE2ETestWorkflow ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          dotnet restore

      - name: Run tests
        run: |
          dotnet test test/Chirp.TestE2E