name: Publish
on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow on any tag starting with 'v'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore src/Chirp.CLI.Client/Chirp.CLI.csproj

      - name: Restore dependencies CSVDB
        run: dotnet restore test/Chirp.CSVDB.Tests/Chirp.CSVDB.Tests.csproj

      - name: Restore dependencies unix
        run: dotnet restore test/Chirp.CLI.Client.Tests/Chirp.CLI.Client.Tests.csproj

      - name: Run tests integration
        run: dotnet test test/Chirp.CSVDB.Tests/Chirp.CSVDB.Tests.csproj --verbosity normal
      
      - name: Run tests unix
        run: dotnet test test/Chirp.CLI.Client.Tests/Chirp.CLI.Client.Tests.csproj --verbosity normal

  release:
    timeout-minutes: 60
    name: Release
    needs: test
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x.x

      - name: Build
        run: dotnet publish src/Chirp.CLI.Client/Chirp.CLI.csproj -c Release -r ${{ matrix.target }} -f net7.0 --no-self-contained  -p:PublishSingleFile=true -o publish/${{ matrix.target }}

      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p Chirp
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            # For Windows, zip all files including the .exe
            7z a Chirp/chirp-${{ matrix.target }}.zip ./publish/${{ matrix.target }}/*
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            # For Linux, zip all files
            zip -j Chirp/chirp-${{ matrix.target }}.zip ./publish/${{ matrix.target }}/*
          else
            # For macOS, zip all files
            zip -j Chirp/chirp-${{ matrix.target }}.zip ./publish/${{ matrix.target }}/*
          fi

      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: chirp-${{ matrix.target }}
          path: Chirp/chirp-${{ matrix.target }}.zip

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Chirp/chirp-${{ matrix.target }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
